#!/bin/sh

systemctl disable opensemanticetl-filemonitoring
systemctl stop opensemanticetl-filemonitoring

systemctl disable opensemanticetl
systemctl stop opensemanticetl

systemctl disable tika
systemctl stop tika

systemctl disable spacy
systemctl stop spacy

systemctl disable flower
systemctl stop flower

systemctl disable solr
systemctl stop solr

exit 0
